name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build . -f Dockerfile -t rushenhansana/servers:cp_camb-${{ github.sha }}
      
      - name: Push the image to Docker Hub (specific tag with SHA)
        run: docker push rushenhansana/servers:cp_camb-${{ github.sha }}
